package(default_visibility = ["//visibility:public"])

config_setting(
  name = "arm64-v8a",
  values = {
    "cpu": "arm64-v8a",
  },
)

config_setting(
  name = "armeabi-v7a",
  values = {
     "cpu": "armeabi-v7a",
  },
)
